import { fonts } from '@repo/design-system/lib/fonts';
import type { Metadata } from 'next';
// import "./globals.css";
import '@repo/design-system/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
